# Site settings
title: Hohoon's Portfolio  
description:  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hohoonzzang.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: HoHoon Cha
user_title: Developer
email: co029@naver.com
github_username:  Chahohoon
gplus_username:

# Google-analytics
google-analytics:
  id: 

exclude: ['package.json', 'src' , 'node_modules']
